# Generated by Django 5.0.6 on 2024-06-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authentication_token',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
